# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_multinom <- function(mat, prop, alpha) {
    .Call(`_DropletUtils_compute_multinom`, mat, prop, alpha)
}

downsample_matrix <- function(rmat, prop, bycol) {
    .Call(`_DropletUtils_downsample_matrix`, rmat, prop, bycol)
}

downsample_runs <- function(cells, reads, prop, bycol) {
    .Call(`_DropletUtils_downsample_runs`, cells, reads, prop, bycol)
}

encode_sequences <- function(Seqs) {
    .Call(`_DropletUtils_encode_sequences`, Seqs)
}

find_swapped <- function(cells, genes, umis, reads, minfrac, diagnostics) {
    .Call(`_DropletUtils_find_swapped`, cells, genes, umis, reads, minfrac, diagnostics)
}

get_cell_barcodes <- function(fname, dname, barcodelen) {
    .Call(`_DropletUtils_get_cell_barcodes`, fname, dname, barcodelen)
}

group_cells <- function(cells, gems) {
    .Call(`_DropletUtils_group_cells`, cells, gems)
}

montecarlo_pval <- function(totalval, totallen, prob, ambient, iterations, alpha, seeds, streams) {
    .Call(`_DropletUtils_montecarlo_pval`, totalval, totallen, prob, ambient, iterations, alpha, seeds, streams)
}

