# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_multinom <- function(mat, prop, alpha) {
    .Call('_DropletUtils_compute_multinom', PACKAGE = 'DropletUtils', mat, prop, alpha)
}

downsample_matrix <- function(rmat, prop, bycol) {
    .Call('_DropletUtils_downsample_matrix', PACKAGE = 'DropletUtils', rmat, prop, bycol)
}

downsample_runs <- function(cells, reads, prop, bycol) {
    .Call('_DropletUtils_downsample_runs', PACKAGE = 'DropletUtils', cells, reads, prop, bycol)
}

encode_sequences <- function(Seqs) {
    .Call('_DropletUtils_encode_sequences', PACKAGE = 'DropletUtils', Seqs)
}

find_chimeric <- function(cells, umis, reads, minfrac, diagnostics) {
    .Call('_DropletUtils_find_chimeric', PACKAGE = 'DropletUtils', cells, umis, reads, minfrac, diagnostics)
}

find_swapped <- function(cells, genes, umis, reads, minfrac, diagnostics) {
    .Call('_DropletUtils_find_swapped', PACKAGE = 'DropletUtils', cells, genes, umis, reads, minfrac, diagnostics)
}

get_cell_barcodes <- function(fname, dname, barcodelen) {
    .Call('_DropletUtils_get_cell_barcodes', PACKAGE = 'DropletUtils', fname, dname, barcodelen)
}

group_cells <- function(cells, gems) {
    .Call('_DropletUtils_group_cells', PACKAGE = 'DropletUtils', cells, gems)
}

hashed_deltas <- function(mat, prop, pseudo_count) {
    .Call('_DropletUtils_hashed_deltas', PACKAGE = 'DropletUtils', mat, prop, pseudo_count)
}

montecarlo_pval <- function(totalval, totallen, prob, ambient, iterations, alpha, seeds, streams) {
    .Call('_DropletUtils_montecarlo_pval', PACKAGE = 'DropletUtils', totalval, totallen, prob, ambient, iterations, alpha, seeds, streams)
}

